import {registry,images,properties} from './builder-schema.js';
import {rowWidth} from './builder-model.js';
import {escapeHtml as e} from './html.js';
const lines=value=>value.split('\n').map(v=>v.trim()).filter(Boolean);
const multiline=value=>e(value).replace(/\n/g,'<br>');
const pairs=value=>lines(value).map(v=>v.split('|').map(x=>x.trim()));
const pad={S:12,M:28,L:48,XL:72};
const photo=(name,asset)=>asset('images/'+name);
const button=(label,attrs='')=>`<button class="pb-button" type="button" ${attrs}>${e(label)}</button>`;
function propertyCard(p,asset,compact=false,details=true){return `<article class="pb-property"><img src="${photo(p.image,asset)}" alt="${e(p.title)}"><div><strong>${new Intl.NumberFormat('ru-RU').format(p.price)} ₽</strong><p>${e(p.info)}</p>${compact?'':`<p>${e(p.title)}</p>`}${details?`<button type="button" class="pb-link" data-property="${p.id}">Подробнее →</button>`:''}</div></article>`;}
export function renderBlock(block,asset){
 const p=block.props;let html='';
 if(block.kind==='hero_slider'){
  const start=images.indexOf(p.image);html=`<div class="pb-hero" style="--hero-height:${p.height}px" data-slider data-auto="${p.auto}">${Array.from({length:p.count},(_,i)=>`<img class="pb-slide" src="${photo(images[(start+i)%images.length],asset)}" alt="Недвижимость Квадрата · слайд ${i+1}" ${i?'hidden':''}>`).join('')}<div class="pb-hero-shade"></div><div class="pb-hero-copy"><p class="pb-eyebrow">${e(p.eyebrow)}</p><h1>${multiline(p.title)}</h1><div class="pb-actions">${button('Заказать консультацию','data-contact')}<button type="button" class="pb-button pb-outline" data-catalog>Смотреть объекты</button></div></div><button type="button" class="pb-next" aria-label="Следующий слайд" data-next>→</button><div class="pb-dots ${p.indicators==='Полоски'?'pb-bars':''}">${Array.from({length:p.count},(_,i)=>`<button type="button" data-slide-index="${i}" aria-label="Слайд ${i+1}" aria-pressed="${i===0}"></button>`).join('')}</div></div>`;
 }
 if(block.kind==='heading')html=`<div style="text-align:${p.align==='Слева'?'left':'center'}"><p class="pb-eyebrow">${e(p.eyebrow)}</p><h2 style="font-size:${p.size}px">${e(p.title)}</h2>${p.line?'<div class="pb-underline"></div>':''}</div>`;
 if(block.kind==='text')html=`<div style="text-align:${p.align==='Слева'?'left':'center'}"><p class="pb-eyebrow">${e(p.eyebrow)}</p><h2>${e(p.title)}</h2><div class="pb-prose" style="--text-columns:${p.columns}">${p.body.split(/\n\s*\n/).map(t=>`<p>${multiline(t)}</p>`).join('')}</div></div>`;
 if(block.kind==='advantages')html=`<div class="pb-grid pb-stats" style="--columns:${p.columns}">${pairs(p.items).map(([value,label],i)=>`<div><strong>${p.style==='Иконки'?['✧','⌂','◇','◷'][i%4]:e(value)}</strong><h3>${e(label||value)}</h3></div>`).join('')}</div>`;
 if(block.kind==='lead_form')html=`<form class="pb-form"><h2>${e(p.title)}</h2><p>${e(p.subtitle)}</p><label>Ваше имя<input name="name" autocomplete="off" required placeholder="Как к вам обращаться"></label><label>${p.fields.includes('email')?'Email':'Телефон'}<input name="contact" type="${p.fields.includes('email')?'email':'tel'}" required placeholder="${p.fields.includes('email')?'name@example.ru':'+7 (___) ___-__-__'}" autocomplete="off"></label>${p.fields.includes('комментарий')?'<label>Комментарий<textarea name="comment" rows="3"></textarea></label>':''}${p.consent?'<label class="pb-consent"><input type="checkbox" required> Согласен на обработку персональных данных</label>':''}<button class="pb-button" type="submit">Отправить заявку</button><small>Демонстрационная форма · данные не отправляются</small><p class="pb-form-result" role="status"></p></form>`;
 if(block.kind==='property_grid'){
  let data=p.source==='Ручной'?lines(p.manual.replace(/,/g,'\n')).map(id=>properties.find(x=>x.id===id)).filter(Boolean):properties.filter(x=>p.filter==='До 10 млн ₽'?x.price<10000000:p.filter==='От 10 млн ₽'?x.price>=10000000:true);
  if(p.sort!=='Сначала новые')data.sort((a,b)=>(a.price-b.price)*(p.sort==='Сначала дешевле'?1:-1));
  const selected=data.slice(0,p.count);html=`<div class="pb-grid" data-listings style="--columns:${Math.min(4,selected.length||1)}">${selected.map(x=>propertyCard(x,asset,p.view==='Компактный')).join('')||'<p>По этим условиям нет объектов в демонстрационной подборке.</p>'}</div><small class="pb-data-note">Пример подборки · ${selected.length} из ${p.count} запрошенных · 4 объекта в библиотеке</small>`;
 }
 if(block.kind==='single_property')html=propertyCard(properties.find(x=>x.id===p.property),asset,p.view==='Компактный',p.button);
 if(block.kind==='photo_gallery')html=`<div class="pb-grid pb-gallery" style="--columns:${p.columns};gap:${({Нет:0,Малый:4,Средний:12,Большой:24})[p.gap]}px">${Array.from({length:p.count},(_,i)=>`<figure>${p.lightbox?`<button type="button" data-lightbox aria-label="Открыть фото ${i+1}">`:''}<img src="${photo(images[(i+3)%images.length],asset)}" alt="Фотография недвижимости ${i+1}">${p.lightbox?'</button>':''}${p.captions?`<figcaption>Недвижимость Квадрата · ${i+1}</figcaption>`:''}</figure>`).join('')}</div>`;
 if(block.kind==='cards')html=`<div class="pb-grid" style="--columns:${Math.min(p.count,3)}">${Array.from({length:p.count},(_,i)=>`<article class="pb-service">${p.media==='Фото'?`<img src="${photo(images[(i+3)%images.length],asset)}" alt="">`:`<span class="pb-service-icon">${['⌂','↗','◇'][i%3]}</span>`}<h3>${e(lines(p.titles)[i]||'Услуга '+(i+1))}</h3><p>Поддержка на каждом этапе сделки</p>${p.link?'<button type="button" class="pb-link" data-contact>Узнать подробнее →</button>':''}</article>`).join('')}</div>`;
 if(block.kind==='carousel')html=`<div class="pb-carousel" data-carousel data-auto="${p.auto}"><div class="pb-carousel-track" style="--columns:${p.columns}">${properties.map((x,i)=>p.kind==='Объекты'?propertyCard(x,asset,false):`<article class="pb-service"><img src="${photo(images[i+3],asset)}" alt=""><h3>${['Покупка','Продажа','Юридическая помощь','Ипотека'][i]}</h3><button type="button" class="pb-link" data-contact>Подробнее →</button></article>`).join('')}</div><div class="pb-carousel-nav"><button type="button" class="pb-button pb-outline" data-scroll="-1" aria-label="Предыдущие карточки">←</button><button type="button" class="pb-button pb-outline" data-scroll="1" aria-label="Следующие карточки">→</button></div></div>`;
 if(block.kind==='accordion')html=`<div class="pb-accordion" data-accordion="${p.mode}">${Array.from({length:p.count},(_,i)=>{const item=pairs(p.items)[i]||['Вопрос '+(i+1),'Добавьте ответ в настройках блока.'];return `<details ${i===0&&p.first?'open':''}><summary>${e(item[0])}</summary><p>${e(item[1]||'')}</p></details>`;}).join('')}</div>`;
 if(block.kind==='cta_banner')html=`<div class="pb-cta" ${p.background==='Фото'?`style="background-image:linear-gradient(120deg,#2f3336eb,#178cbe88),url('${photo('city-aerial-2.png',asset)}')"`:''}><div><h2>${e(p.title)}</h2><p>${e(p.body)}</p></div>${button(p.button,'data-contact')}</div>`;
 const special=['hero_slider','cta_banner'].includes(block.kind);
 return `<div class="pb-content pb-bg-${({Белый:'white',Светлый:'wash',Тёмный:'dark'})[p.backgroundColor]} ${special?'pb-edge':''}" style="--block-pad:${pad[p.padding]}px">${html}</div>`;
}
export function renderPage(page,{asset,editing=false,selected=null,placing=null}={}){
 const insert=beforeId=>`<button type="button" class="pb-insert ${placing?'is-placing':''}" data-before="${beforeId||''}"><span>＋</span> ${placing?'Вставить новой строкой':'Добавить блок'}</button>`;
 return `<div class="pb-page ${editing?'pb-editing':''}">${editing?insert(page.rows[0]?.id):''}${page.rows.map(row=>{
  const free=12-rowWidth(row),min=placing?.kind?registry[placing.kind].min:placing?.id?registry[page.rows.flatMap(r=>r.blocks).find(b=>b.id===placing.id)?.kind]?.min:0;
  return `<div class="pb-row" data-row-id="${row.id}">${row.blocks.map(block=>`<section class="pb-block ${selected===block.id?'is-selected':''}" style="--span:${block.span}" data-block-id="${block.id}" aria-label="${e(registry[block.kind].name)}">${renderBlock(block,asset)}${editing?`<button type="button" class="pb-select-block" data-select="${block.id}" aria-label="Редактировать: ${e(registry[block.kind].name)}"></button><div class="pb-block-tools"><button type="button" class="pb-block-tag" data-drag-block="${block.id}" data-select="${block.id}" title="Перетащить блок">⠿ ${e(registry[block.kind].name)} · ${block.span}/12</button><div><button type="button" data-move="-1" data-id="${block.id}" aria-label="Переместить блок назад">↑</button><button type="button" data-move="1" data-id="${block.id}" aria-label="Переместить блок вперёд">↓</button><button type="button" data-duplicate="${block.id}" aria-label="Дублировать блок">⧉</button><button type="button" data-delete="${block.id}" aria-label="Удалить блок">×</button></div></div>${registry[block.kind].min<12?`<button class="pb-resize" type="button" data-resize="${block.id}" aria-label="Изменить ширину блока стрелками" title="Потяните или используйте стрелки ← →"></button>`:''}`:''}</section>`).join('')}${editing&&free?`<button type="button" class="pb-free ${placing?(free>=min?'fits':'tight'):''}" style="--span:${free}" data-into="${row.id}" aria-disabled="${!!placing&&free<min}">${placing?(free>=min?'＋ Вставить в строку':'Недостаточно места'):'Свободное место'}<small>${free} из 12 колонок${placing&&free<min?` · нужно ${min}`:''}</small></button>`:''}${editing&&!free&&placing?'<span class="pb-full-note">Строка заполнена · вставьте блок между строками</span>':''}</div>${editing?insert(page.rows[page.rows.indexOf(row)+1]?.id):''}`;
 }).join('')}${!page.rows.length?'<div class="pb-empty-page"><h2>Начните свою страницу</h2><p>Выберите первый блок в библиотеке.</p></div>':''}</div>`;
}
