import {registry,fieldsFor} from './builder-schema.js';
import {PageModel,initialPage,validatePage,findBlock,rowWidth} from './builder-model.js';
import {renderPage} from './builder-render.js';
import {previewRuntime} from './builder-preview.js';
import {escapeHtml as e} from './html.js';
const storageKey='kvadrat.page-builder.v1';
const devices={desktop:{width:1280,label:'Десктоп',icon:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>'},tablet:{width:834,label:'Планшет',icon:'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M11 19h2"/>'},mobile:{width:390,label:'Смартфон',icon:'<rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 19h2"/>'}};
let sessionPage=null;
export function mountBuilder(main,{asset,toast}){
 let stored=null,storageWarning=false;
 try{const text=localStorage.getItem(storageKey);if(text)stored=validatePage(JSON.parse(text).page);}catch{storageWarning=true;}
 const model=new PageModel(sessionPage||stored||initialPage());
 let selected=model.page.rows[3]?.blocks[0]?.id||null,placing=null,device='desktop',preview=false,search='',pane='canvas',saveTimer,disposed=false,saveLabel=stored?'Черновик восстановлен в этом браузере':'Исходный макет · можно редактировать',previewRequest=0;
 const abort=new AbortController();
 const listen=(node,event,handler,options={})=>node.addEventListener(event,handler,{...options,signal:abort.signal});
 document.body.classList.add('builder-open');
 main.innerHTML=`<section class="pb-editor" data-pane="canvas" data-preview="false"><header class="pb-toolbar"><a class="pb-back" href="#pages" aria-label="Все страницы" title="Все страницы">←</a><div class="pb-title"><input id="pb-title" aria-label="Название страницы" maxlength="160" value="${e(model.page.title)}"><div class="pb-save-state" role="status"></div></div><div class="pb-devices" aria-label="Размер страницы">${Object.entries(devices).map(([id,d])=>`<button type="button" data-device="${id}" title="${d.label}" aria-label="${d.label}" aria-pressed="${id===device}"><svg viewBox="0 0 24 24" aria-hidden="true">${d.icon}</svg></button>`).join('')}</div><div class="pb-history"><button type="button" class="pb-icon-button" data-command="undo" aria-label="Отменить" title="Отменить · Ctrl+Z">↶</button><button type="button" class="pb-icon-button" data-command="redo" aria-label="Повторить" title="Повторить · Ctrl+Shift+Z">↷</button></div><button class="btn outline sm" type="button" data-command="preview">Предпросмотр</button><button class="btn outline sm" type="button" data-command="save">Сохранить</button><button class="btn sm pb-export-button" type="button" data-command="export" aria-label="Экспорт и импорт"><span class="pb-export-label">Экспорт</span></button></header><nav class="pb-mobile-tabs" aria-label="Панели конструктора">${[['library','Блоки'],['canvas','Страница'],['settings','Настройки']].map(([id,t])=>`<button type="button" data-pane-button="${id}" aria-selected="${id===pane}">${t}</button>`).join('')}</nav><div class="pb-body"><aside class="pb-library"><div class="pb-panel-heading"><h2>Библиотека блоков <span class="pb-status-badge">12</span></h2><input class="pb-search" type="search" aria-label="Поиск блока" placeholder="Поиск блока"><p>Выберите блок и место вставки. Можно перетащить его на страницу.</p></div><div class="pb-library-list"></div><a class="pb-source-ref" href="#file/${encodeURIComponent('kvadrat-ds/source/page-builder/PageBuilder.dc.html')}">Открыть исходный макет ↗</a></aside><div class="pb-stage"><div class="pb-canvas-caption"></div><div class="pb-sizer"><div class="pb-canvas"></div></div></div><aside class="pb-inspector" aria-label="Настройки блока"></aside></div><dialog class="pb-dialog" aria-labelledby="pb-dialog-title"></dialog><input type="file" id="pb-import" accept="application/json,.json" hidden></section>`;
 const root=main.querySelector('.pb-editor'),canvas=root.querySelector('.pb-canvas'),stage=root.querySelector('.pb-stage'),sizer=root.querySelector('.pb-sizer'),inspector=root.querySelector('.pb-inspector'),dialog=root.querySelector('.pb-dialog');
 function status(){root.querySelector('.pb-save-state').textContent=saveLabel;root.querySelector('[data-command=undo]').disabled=!model.past.length;root.querySelector('[data-command=redo]').disabled=!model.future.length;}
 function save(notify=false){clearTimeout(saveTimer);sessionPage=structuredClone(model.page);try{localStorage.setItem(storageKey,JSON.stringify({page:model.page,savedAt:new Date().toISOString()}));saveLabel='Сохранено в этом браузере · '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});if(notify)toast('Черновик сохранён в этом браузере');}catch{saveLabel='Не удалось сохранить · скачайте JSON';if(notify)toast('Память браузера недоступна. Сохраните черновик через экспорт JSON.');}status();}
 function changed({settings=true}={}){sessionPage=structuredClone(model.page);saveLabel='Сохраняем черновик…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(),500);if(selected&&!findBlock(model.page,selected))selected=null;drawCanvas();if(settings)drawInspector();status();}
 function setPane(value){pane=value;root.dataset.pane=pane;root.querySelectorAll('[data-pane-button]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.paneButton===pane)));requestAnimationFrame(fit);}
 function fit(){if(disposed||!stage.clientWidth)return;const width=devices[device].width,scale=Math.min(1,Math.max(.1,(stage.clientWidth-52)/width));canvas.style.width=width+'px';canvas.style.transform=`scale(${scale})`;sizer.style.width=width*scale+'px';const iframe=canvas.querySelector('iframe');if(iframe)iframe.style.height=Math.max(620,(stage.clientHeight-85)/scale)+'px';sizer.style.height=canvas.offsetHeight*scale+'px';}
 const observer=new ResizeObserver(fit);observer.observe(stage);observer.observe(canvas);
 function drawLibrary(){const list=root.querySelector('.pb-library-list');list.innerHTML=['Медиа','Недвижимость','Контент','Действие'].map(category=>{const entries=Object.entries(registry).filter(([,r])=>r.category===category&&r.name.toLowerCase().includes(search));return entries.length?`<p class="pb-group-name">${category}</p>${entries.map(([kind,r])=>`<button type="button" class="pb-library-item" data-kind="${kind}" aria-pressed="${placing?.kind===kind}"><span class="pb-item-icon" aria-hidden="true">${r.icon}</span><span><strong>${r.name}</strong><small>${r.width===12?'Полная ширина':r.width+'/12 колонок'} · мин. ${r.min}</small></span><span aria-hidden="true">⠿</span></button>`).join('')}`:'';}).join('')||'<p class="pb-hint">Блоки не найдены. Измените запрос.</p>';}
 function caption(){const d=devices[device];root.querySelector('.pb-canvas-caption').innerHTML=`<span>${d.label} · <strong>${d.width} px</strong></span>${placing?`<span>Вставка: ${registry[placing.kind||findBlock(model.page,placing.id)?.block.kind]?.name||'блок'}</span><button type="button" data-command="cancel-place">Отмена</button>`:`<span>${model.page.rows.length} строк · ${model.page.rows.reduce((n,r)=>n+r.blocks.length,0)} блоков${preview?' · предпросмотр':''}</span>`}`;}
 async function pageDocument(inline=false){
  const page=structuredClone(model.page);
  const base=new URL('.',location.href),absoluteAsset=name=>new URL(asset(name),base).href;
  const cssPaths=['references/kvadrat-ds/tokens/fonts.css','references/kvadrat-ds/tokens/colors.css','references/kvadrat-ds/tokens/shadows.css','builder-page.css'];
  let content=renderPage(page,{asset:absoluteAsset});
  let styles=cssPaths.map(path=>`<link rel="stylesheet" href="${new URL(path,base).href}">`).join('');
  if(inline){
   const dataUrl=async url=>{const response=await fetch(url);if(!response.ok)throw Error('Не удалось загрузить ресурс');const blob=await response.blob();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});};
   const css=await Promise.all(cssPaths.map(async path=>{const url=new URL(path,base),response=await fetch(url);if(!response.ok)throw Error('Не удалось загрузить стили');let value=await response.text();const urls=[...value.matchAll(/url\(['"]?([^'"\)]+)['"]?\)/g)];for(const match of urls)value=value.replace(match[0],`url('${await dataUrl(new URL(match[1],url))}')`);return value;}));
   styles=`<style>${css.join('\n')}</style>`;
   const urls=[...new Set([...content.matchAll(/(?:src="|url\(')(https?:[^"']+)/g)].map(m=>m[1]))];
   for(const url of urls)content=content.split(url).join(await dataUrl(url));
  }
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(page.title)} — Квадрат</title>${styles}<style>body{margin:0;background:#fff;font-family:var(--font-sans),sans-serif}button,input,textarea{font:inherit}*{box-sizing:border-box}</style></head><body>${content}<script>(${previewRuntime.toString()})();<`+'/script></body></html>';
 }
 function drawCanvas(){caption();const request=++previewRequest;if(preview){canvas.innerHTML='<iframe class="pb-preview-frame" title="Предпросмотр страницы" sandbox="allow-scripts allow-forms"></iframe>';pageDocument().then(html=>{if(!disposed&&request===previewRequest){canvas.querySelector('iframe').srcdoc=html;fit();}}).catch(()=>toast('Не удалось открыть предпросмотр'));}else{canvas.innerHTML=renderPage(model.page,{asset,editing:true,selected,placing});canvas.querySelectorAll('.pb-content').forEach(content=>content.inert=true);}requestAnimationFrame(fit);}
 function field(f,b){const value=b.props[f.key],id='pb-field-'+f.key;const attrs=`id="${id}" data-prop="${f.key}"`;
  if(f.key==='manual'&&b.props.source!=='Ручной'||f.key==='filter'&&b.props.source!=='Фильтр'||f.key==='backgroundColor'&&['hero_slider','cta_banner'].includes(b.kind))return '';
  if(f.type==='checkbox')return `<label class="pb-field pb-check"><input ${attrs} type="checkbox" ${value?'checked':''}>${e(f.label)}</label>`;
  return `<label class="pb-field" for="${id}">${e(f.label)}${f.type==='select'?`<select ${attrs}>${f.options.map(o=>`<option ${o===value?'selected':''} value="${e(o)}">${e(o)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea ${attrs} maxlength="5000" rows="5">${e(value)}</textarea>`:`<input ${attrs} type="${f.type}" value="${e(value)}" ${f.type==='number'?`min="${f.min}" max="${f.max}" step="1"`:'maxlength="5000"'}>`}</label>`;
 }
 function drawInspector(){const entry=findBlock(model.page,selected);if(!entry){inspector.innerHTML='<div class="pb-empty-inspector"><span>⌖</span><h2>Выберите блок</h2><p>Нажмите на блок страницы, чтобы изменить содержимое, ширину и оформление.</p></div>';return;}
  const {block:b,row}=entry,r=registry[b.kind],max=12-rowWidth(row)+b.span;
  inspector.innerHTML=`<div class="pb-panel-heading"><span class="pb-item-icon">${r.icon}</span><div><h2>${r.name}</h2><p>${b.kind}</p></div></div><div class="pb-inspector-body"><p class="pb-section-label">Ширина · колонки сетки</p><div class="pb-width-cells">${Array.from({length:12},(_,i)=>`<button type="button" data-width="${i+1}" ${i+1<r.min||i+1>max?'disabled':''} class="${i<b.span?'filled':''}" aria-label="${i+1} из 12 колонок" aria-pressed="${i+1===b.span}">${i+1===b.span?i+1:''}</button>`).join('')}</div><div class="pb-width-summary"><span>Занимает <strong>${b.span}</strong> из 12 колонок</span><span class="pb-shrink">Сжатие: ${r.shrink}</span></div><input class="pb-width-range" aria-label="Ширина блока" type="range" min="${r.min}" max="${max}" value="${b.span}" ${max===r.min?'disabled':''}><div class="pb-presets">${[['1/1',12],['2/3',8],['1/2',6],['1/3',4]].map(([label,n])=>`<button type="button" data-width="${n}" ${n<r.min||n>max?'disabled':''}>${label}</button>`).join('')}</div><p class="pb-hint">${r.min===12?'Только полная ширина строки.':`Минимум ${r.min} колонок. В этой строке доступно до ${max}.`}</p><p class="pb-section-label">Настройки блока</p>${fieldsFor(b.kind).map(f=>field(f,b)).join('')}<p class="pb-section-label">Расположение</p><label class="pb-field">Переместить в строку<select id="pb-move-row"><option value="">Выберите место…</option>${model.page.rows.filter(other=>other!==row).map(other=>{const free=12-rowWidth(other);return `<option value="${other.id}" ${free<r.min?'disabled':''}>Строка ${model.page.rows.indexOf(other)+1} · свободно ${free}/12</option>`;}).join('')}<option value="new">Новая строка в конце</option></select></label><div class="pb-inspector-actions"><button type="button" data-move="-1" data-id="${b.id}">↑ Раньше</button><button type="button" data-move="1" data-id="${b.id}">↓ Позже</button><button type="button" data-duplicate="${b.id}">Дублировать</button><button type="button" data-delete="${b.id}">Удалить</button></div><p class="pb-hint">Удаление и перестановку можно отменить. На смартфоне блоки автоматически идут друг под другом.</p></div>`;
 }
 function run(action){try{action();}catch(error){toast(error.message||'Не удалось выполнить действие');}}
 function place(target,payload=placing){if(!payload){setPane('library');toast('Выберите блок в библиотеке');return;}run(()=>{selected=model.place(payload,target);placing=null;changed();drawLibrary();setPane('canvas');});}
 function selectBlock(id){selected=id;placing=null;model.mergeKey=null;drawCanvas();drawInspector();drawLibrary();setPane('settings');}
 function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function showExport(){dialog.innerHTML=`<button type="button" class="pb-dialog-close" data-command="close-dialog" aria-label="Закрыть">×</button><h2 id="pb-dialog-title">Сохранить страницу</h2><p>Черновик хранится в этом браузере. JSON позволяет перенести его и продолжить редактирование. HTML — самостоятельная страница с изображениями и шрифтами.</p><div class="row"><button class="btn sm" data-command="json">Скачать JSON</button><button class="btn outline sm" data-command="html">Скачать HTML</button><button class="btn outline sm" data-command="import">Загрузить JSON</button></div><p class="pb-export-note">Это дизайн-макет. Формы демонстрационные, объекты взяты из библиотеки. Публикация в приложении Квадрата не подключена.</p><button class="btn text" data-command="reset">Вернуть исходный макет</button>`;dialog.showModal();}
 async function command(name){
  if(name==='undo'||name==='redo'){model[name]();placing=null;root.querySelector('#pb-title').value=model.page.title;changed();drawLibrary();}
  if(name==='save')save(true);
  if(name==='preview'){preview=!preview;placing=null;root.dataset.preview=String(preview);root.querySelector('[data-command=preview]').textContent=preview?'← Редактор':'Предпросмотр';drawCanvas();setPane('canvas');}
  if(name==='cancel-place'){placing=null;drawCanvas();drawLibrary();}
  if(name==='export')showExport();
  if(name==='close-dialog')dialog.close();
  if(name==='json'){download(JSON.stringify(model.page,null,2),'application/json','kvadrat-page.json');toast('Черновик выгружен в JSON');}
  if(name==='html'){const b=dialog.querySelector('[data-command=html]');b.disabled=true;b.textContent='Собираем страницу…';try{const html=await pageDocument(true);download(html,'text/html','kvadrat-page.html');toast('HTML с изображениями и шрифтами готов');}catch{toast('Не удалось собрать HTML. Попробуйте ещё раз.');}finally{b.disabled=false;b.textContent='Скачать HTML';}}
  if(name==='import')root.querySelector('#pb-import').click();
  if(name==='reset'){model.replace(initialPage());selected=model.page.rows[3].blocks[0].id;root.querySelector('#pb-title').value=model.page.title;dialog.close();changed();toast('Исходный макет восстановлен. Это действие можно отменить.');}
 }
 listen(root,'click',event=>{
  const b=event.target.closest('button');if(!b)return;
  if(b.dataset.command){command(b.dataset.command).catch(error=>toast(error.message));return;}
  if(b.dataset.device){device=b.dataset.device;root.querySelectorAll('[data-device]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));caption();fit();return;}
  if(b.dataset.paneButton){setPane(b.dataset.paneButton);return;}
  if(b.dataset.kind){placing={kind:b.dataset.kind};drawLibrary();drawCanvas();setPane('canvas');return;}
  if(b.hasAttribute('data-before')){place({beforeId:b.dataset.before||null});return;}
  if(b.dataset.into){place({rowId:b.dataset.into});return;}
  if(b.dataset.select){selectBlock(b.dataset.select);return;}
  run(()=>{if(b.dataset.width){model.resize(selected,Number(b.dataset.width));changed();}if(b.dataset.duplicate){selected=model.duplicate(b.dataset.duplicate);changed();}if(b.dataset.delete){model.remove(b.dataset.delete);changed();}if(b.dataset.move){model.move(b.dataset.id,Number(b.dataset.move));changed();}});
 });
 listen(root,'input',event=>{
  const input=event.target;
  if(input.matches('.pb-search')){search=input.value.toLowerCase();drawLibrary();return;}
  if(input.id==='pb-title'){run(()=>{model.change(page=>page.title=input.value,'title');changed({settings:false});});return;}
  if(input.matches('.pb-width-range')){model.resize(selected,Number(input.value),'width:'+selected);changed({settings:false});return;}
  if(input.dataset.prop){const f=fieldsFor(findBlock(model.page,selected).block.kind).find(f=>f.key===input.dataset.prop);if(f.type==='number'&&!input.validity.valid)return;const value=f.type==='checkbox'?input.checked:f.type==='number'?Number(input.value):input.value;run(()=>{model.update(selected,f.key,value,'field:'+selected+':'+f.key);changed({settings:false});});}
 });
 listen(root,'change',event=>{const input=event.target;if(input.matches('.pb-width-range')||input.dataset.prop){model.mergeKey=null;drawInspector();}if(input.id==='pb-move-row'&&input.value)place(input.value==='new'?{}:{rowId:input.value},{id:selected});});
 listen(root.querySelector('#pb-import'),'change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>2*1024*1024)throw Error('Файл слишком большой. Максимум — 2 МБ.');const page=validatePage(JSON.parse(await file.text()));model.replace(page);selected=page.rows[0]?.blocks[0]?.id||null;root.querySelector('#pb-title').value=page.title;dialog.close();changed();toast('Черновик загружен. Импорт можно отменить.');}catch(error){toast('Не удалось импортировать: '+error.message);}});
 function dropTarget(event){const node=event.target.closest('[data-before],[data-into],.pb-block');if(!node)return null;if(node.hasAttribute('data-before'))return {node,target:{beforeId:node.dataset.before||null}};if(node.hasAttribute('data-into'))return {node,target:{rowId:node.dataset.into}};const row=node.closest('.pb-row'),rect=row.getBoundingClientRect(),index=model.page.rows.findIndex(r=>r.id===row.dataset.rowId),before=event.clientY<rect.top+rect.height/2;return {node,target:{beforeId:model.page.rows[index+(before?0:1)]?.id||null}};}
 let suppressDragClick=false;
 listen(root,'pointerdown',()=>suppressDragClick=false,{capture:true});
 listen(root,'click',event=>{if(suppressDragClick){event.preventDefault();event.stopImmediatePropagation();suppressDragClick=false;}},{capture:true});
 listen(root,'pointerdown',event=>{
  const handle=event.target.closest('[data-drag-block],[data-kind]');if(!handle||event.button!==0)return;
  const payload=handle.dataset.kind?{kind:handle.dataset.kind}:{id:handle.dataset.dragBlock},startX=event.clientX,startY=event.clientY;
  let dragging=false,drop=null;handle.setPointerCapture(event.pointerId);
  const move=ev=>{if(!dragging&&Math.hypot(ev.clientX-startX,ev.clientY-startY)<7)return;dragging=true;root.classList.add('pb-dragging');const under=document.elementFromPoint(ev.clientX,ev.clientY);drop=under?dropTarget({target:under,clientY:ev.clientY}):null;root.querySelectorAll('.pb-drop-target').forEach(el=>el.classList.remove('pb-drop-target'));drop?.node.classList.add('pb-drop-target');const rect=stage.getBoundingClientRect();if(ev.clientX>rect.left&&ev.clientX<rect.right){if(ev.clientY>rect.bottom-40)stage.scrollTop+=18;if(ev.clientY<rect.top+65)stage.scrollTop-=18;}};
  const end=ev=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',end);document.removeEventListener('pointercancel',end);if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);root.classList.remove('pb-dragging');root.querySelectorAll('.pb-drop-target').forEach(el=>el.classList.remove('pb-drop-target'));if(dragging){suppressDragClick=true;if(ev.type==='pointerup'&&drop)place(drop.target,payload);}};
  document.addEventListener('pointermove',move,{signal:abort.signal});document.addEventListener('pointerup',end,{signal:abort.signal});document.addEventListener('pointercancel',end,{signal:abort.signal});
 });
 listen(root,'pointerdown',event=>{const handle=event.target.closest('[data-resize]');if(!handle||event.button!==0)return;event.preventDefault();const id=handle.dataset.resize,entry=findBlock(model.page,id),start=event.clientX,span=entry.block.span,rowPixels=handle.closest('.pb-row').getBoundingClientRect().width;const move=ev=>{model.resize(id,span+(ev.clientX-start)*12/rowPixels,'resize:'+id);changed({settings:false});};const end=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',end);document.removeEventListener('pointercancel',end);model.mergeKey=null;drawInspector();};document.addEventListener('pointermove',move,{signal:abort.signal});document.addEventListener('pointerup',end,{signal:abort.signal});document.addEventListener('pointercancel',end,{signal:abort.signal});});
 listen(document,'keydown',event=>{
  if(event.key==='Escape'&&placing){placing=null;drawCanvas();drawLibrary();return;}
  const target=event.target;
  if(target.matches('[data-resize]')&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();model.resize(target.dataset.resize,findBlock(model.page,target.dataset.resize).block.span+(event.key==='ArrowRight'?1:-1));changed();canvas.querySelector(`[data-resize="${target.dataset.resize}"]`)?.focus();return;}
  if(target.matches('input,textarea,select')||target.isContentEditable||dialog.open)return;
  if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();command(event.shiftKey?'redo':'undo');}
  if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save(true);}
 });
 listen(dialog,'click',event=>{if(event.target===dialog)dialog.close();});
 listen(window,'pagehide',()=>save());
 drawLibrary();drawCanvas();drawInspector();status();if(storageWarning)toast('Сохранённый черновик недоступен. Открыт исходный макет.');
 return ()=>{disposed=true;clearTimeout(saveTimer);if(sessionPage)save();observer.disconnect();abort.abort();if(dialog.open)dialog.close();document.body.classList.remove('builder-open');};
}
