const groups={homepage:'Публичная главная',admin:'Админ-панель',scheduling:'Встречи и расписание',topbar:'Меню пользователя'};
const titles={
 '01-admin-shell':'Каркас админ-панели','02-feed-list':'Список импорт-фидов','03-feed-edit-form':'Форма импорт-фида','04-feed-import-mapping':'Маппинг полей','05-block-catalog':'Каталог блоков','06-page-builder':'Конструктор страниц','07-login':'Вход в аккаунт',
 '01-admin-week':'Занятость юриста · неделя','02-admin-new-week':'Новая неделя','03-admin-busy-popover':'Редактирование занятости','04-admin-tooltip':'Подсказка в расписании','05-admin-toast-saved':'Уведомление о сохранении','06-employee-step1-lawyer':'Выбор юриста','07-employee-step2-type':'Тип встречи','08-employee-step2-detail':'Детали встречи','09-employee-step3-grid':'Выбор времени','10-employee-no-free-slots':'Нет свободных слотов','11-employee-loading':'Загрузка расписания'};
const homeTitles=['Шапка и первый экран','Услуги агентства','Услуги и ипотека','Ипотека и промоблок','Риэлторы и каталог объектов','Каталог, поиск и команда','Команда и текстовый блок','Текстовый блок и заявка','Заявка, новости и блог','Блог и подвал'];
const templateSources=['admin/Admin.dc.html','feed-list/FeedList.dc.html','feed-edit/FeedEdit.dc.html','feed-import/FeedImport.dc.html','block-catalog/BlockCatalog.dc.html','page-builder/PageBuilder.dc.html','login/Login.dc.html'];
export async function renderLibrary(section,detail,main,ctx){
 const {catalog,escapeHtml:e,ref,heading}=ctx;
 const fileLink=path=>`#file/${encodeURIComponent(path)}`;
 const screenFiles=catalog.files.filter(f=>f.path.includes('/screenshots/'));
 const screens=screenFiles.map(f=>{const base=f.path.split('/').pop().replace('.png','');const group=f.path.includes('appointments')?'scheduling':f.path.includes('/homepage/')?'homepage':'admin';const n=parseInt(base,10);return {...f,group,title:group==='homepage'?homeTitles[n-1]:titles[base]||base,source:group==='scheduling'?'design_handoff_appointments/source/Appointments.dc.html':group==='homepage'?'kvadrat-ds/source/homepage/App.md':`kvadrat-ds/source/${templateSources[n-1]}`}});
 const tabs=(items,active)=>`<nav class="tabs" aria-label="Разделы">${items.map(([id,title,href])=>`<a ${active===id?'class="active" aria-current="page"':''} href="${href}">${title}</a>`).join('')}</nav>`;
 if(section==='screens'){
  const current=Object.hasOwn(groups,detail)?detail:'';
  main.innerHTML=heading('Архив макетов','Исходные скриншоты и эталоны из дизайн-хендоффов для сверки. Все свёрстанные страницы собраны в разделе «Все страницы».','Скриншоты и эталоны','28 скриншотов + меню')+'<p class="archive-pages-link"><a class="inline-link" href="#pages">← Все страницы проекта</a></p>'+tabs([['','Все эталоны','#screens'],...Object.entries(groups).map(([id,title])=>[id,title,`#screens/${id}`])],current)+
  (current==='scheduling'?`<aside class="notice"><strong>Исторические скриншоты</strong><p>Сетка на этих снимках предшествует повороту календаря: в актуальном исходнике дни расположены по колонкам, часы — по строкам. Порядок записи в приложении: тип → юрист → время.</p><a href="${fileLink('kvadrat-ds/MAP.md')}">Открыть пояснения к макетам →</a></aside>`:'')+
  (!current||current==='homepage'?`<section class="panel" style="margin-bottom:26px"><p class="eyebrow">Публичный сайт</p><h2 style="margin:12px 0">Свёрстанные страницы из Figma</h2><p style="margin:0 0 20px;color:#60727e">Главная, каталог недвижимости и страница отдельного объекта.</p><div class="row"><a class="btn" href="homepage.html">Главная →</a><a class="btn outline" href="property-catalog.html">Каталог недвижимости</a><a class="btn outline" href="property-object.html">Страница объекта</a><a class="inline-link" href="homepage-components.html">Компоненты главной</a></div></section>`:'')+
  (!current||current==='admin'?`<section class="panel" style="margin-bottom:24px"><h2>Импорт-фиды</h2><p style="margin:8px 0 16px;color:#60727e">Интерактивные макеты: источники, настройки и сопоставление полей с проверкой образца.</p><div class="row"><a class="btn" href="feeds.html">Открыть список фидов →</a><a class="btn outline" href="feeds.html#feed/cian-msk-resale/mapping">Маппинг полей</a><a class="inline-link" href="feeds-ux.html">Что улучшено в UX</a></div></section>`:'')+
  (!current||current==='admin'?`<p class="section-note" style="margin:0 0 20px">Макеты сохраняют исходный замысел. Принятые изменения поведения приложения отмечены в <a class="inline-link" href="${fileLink('kvadrat-ds/MAP.md')}">карте экранов</a>.</p>`:'')+
  `<div class="screen-grid">${screens.filter(s=>!current||s.group===current).map(s=>`<article class="screen-card"><button class="screen-preview" data-screen="${e(s.path)}" aria-label="Открыть макет: ${e(s.title)}"><img src="${ref(s.path)}" alt="${e(s.title)}" loading="lazy"><span>Рассмотреть макет ↗</span></button><div class="screen-caption"><p class="meta">${groups[s.group]}${s.group==='scheduling'?' · исторический':''}</p><h3>${e(s.title)}</h3>${s.source.includes("page-builder")?'<a class="btn sm" href="#builder" style="margin-bottom:12px">Открыть конструктор →</a><br>':''}<a class="inline-link" href="${fileLink(s.source)}">Исходник</a></div></article>`).join('')}
  ${!current||current==='topbar'?`<article class="screen-card"><button class="screen-preview topbar-cover" id="open-topbar" aria-label="Открыть макет: Меню пользователя"><div class="mini-header"><span>Админ-панель</span><span class="initials">АИ</span></div><div class="mini-menu"><strong>Александр Иванов</strong><small>Администратор</small><span>Настройки профиля</span><span>Выход</span></div><span>Десктоп и мобильный ↗</span></button><div class="screen-caption"><p class="meta">Меню пользователя · HTML-эталон</p><h3>Меню в верхней панели</h3><a class="inline-link" href="${fileLink('design_handoff_topbar_user_menu/Topbar.vue')}">Исходник Vue</a></div></article>`:''}</div>`;
  main.querySelectorAll('[data-screen]').forEach(button=>button.onclick=()=>{const screen=screens.find(s=>s.path===button.dataset.screen);openViewer(screen.title,`<p class="viewer-description">${screen.group==='scheduling'?'Историческое состояние. Обновлённая сетка — в исходнике.':'Оригинальный скриншот из дизайн-хендоффа.'} <a class="inline-link" href="${ref(screen.path)}" download>Скачать изображение</a></p><img src="${ref(screen.path)}" alt="${e(screen.title)}">`)});
  const topbar=main.querySelector('#open-topbar');if(topbar)topbar.onclick=async()=>{try{const text=await getText('design_handoff_topbar_user_menu/reference/topbar-user-menu.html');openViewer('Меню пользователя · два размера','<iframe class="topbar-frame" title="Эталон меню пользователя: десктоп и мобильный" sandbox=""></iframe>');const styles=['fonts','colors','typography','spacing','shadows'].map(name=>`<link rel="stylesheet" href="${new URL(ref(`kvadrat-ds/tokens/${name}.css`),location.href).href}">`).join('');document.querySelector('.topbar-frame').srcdoc=text.replace('<link rel="stylesheet" href="../../styles.css">',styles)}catch{ctx.toast('Не удалось загрузить макет. Попробуйте ещё раз.')}};
  return;
 }
 if(section==='components'){
  const {renderComponents}=await import('./components.js');return renderComponents(detail,main,ctx);
 }
 if(section==='file'){
  const path=decodeURIComponent(detail);const file=catalog.files.find(f=>f.path===path);
  if(!file){main.innerHTML=heading('Файл не найден','Вернитесь в каталог, чтобы выбрать материал.')+'<a class="btn outline" href="#sources">К исходным файлам</a>';return}
  const textType=/\.(md|js|html|css|vue)$/.test(path);
  main.innerHTML=heading(path.split('/').pop(),'Оригинальный материал из docs/design.','Исходный файл')+`<div class="file-toolbar"><a class="btn outline sm" href="#sources">← Все файлы</a><a class="btn outline sm" href="${ref(path)}" download>Скачать файл</a><span class="meta">${e(path)}</span></div>${path.includes("page-builder/PageBuilder")?'<p style="margin-bottom:20px"><a class="btn" href="#builder">Открыть интерактивный конструктор →</a></p>':''}<section id="file-body" class="panel document"></section>`;
  const body=main.querySelector('#file-body');
  if(textType){const text=await getText(path);if(!body.isConnected)return;body.innerHTML=path.endsWith('.md')?markdown(text,e):`<pre><code>${e(text)}</code></pre>`}
  else if(/\.(png|jpg|svg)$/.test(path))body.innerHTML=`<img src="${ref(path)}" alt="${e(path.split('/').pop())}" class="asset-preview">`;
  else body.innerHTML='<p>Файл шрифта доступен для скачивания. Образцы семейства — в разделе «Типографика».</p>';
  return;
 }
 main.innerHTML=heading('Исходные файлы','Оригиналы всех трёх хендоффов: структура, значения, состояния и изображения.','Материалы дизайн-системы',`${catalog.files.length} файлов`)+`<div class="file-toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><input id="file-search" type="search" placeholder="Найти файл или компонент" aria-label="Поиск исходных файлов"></label><label class="select-label">Тип<select id="file-type"><option value="">Все файлы</option value="md">Описания</option><option value="html">Макеты HTML</option><option value="css">Токены CSS</option><option value="image">Изображения</option><option value="ttf">Шрифты</option><option value="code">JS и Vue</option></select></label><span id="file-count" class="meta" aria-live="polite"></span></div><div class="file-list" id="file-list"></div>`;
 const drawFiles=()=>{const term=main.querySelector('#file-search').value.toLowerCase();const type=main.querySelector('#file-type').value;const filtered=catalog.files.filter(f=>f.path.toLowerCase().includes(term)&&(!type||(type==='image'?/\.(png|jpg|svg)$/.test(f.path):type==='code'?/\.(js|vue)$/.test(f.path):f.path.endsWith('.'+type))));main.querySelector('#file-count').textContent=`${filtered.length} из ${catalog.files.length}`;main.querySelector('#file-list').innerHTML=filtered.length?filtered.map(f=>`<a class="file-row" href="${fileLink(f.path)}"><span class="file-extension">${f.path.split('.').pop().toUpperCase()}</span><span><strong>${e(f.path.split('/').pop())}</strong><small>${e(f.path)}</small></span><span class="file-size">${f.size<1024?f.size+' Б':f.size<1048576?Math.round(f.size/1024)+' КБ':(f.size/1048576).toFixed(1)+' МБ'}</span><span aria-hidden="true">↗</span></a>`).join(''):'<div class="panel"><h3>Файлы не найдены</h3><p>Измените запрос или выберите другой тип.</p></div>'};
 main.querySelector('#file-search').oninput=drawFiles;main.querySelector('#file-type').onchange=drawFiles;drawFiles();
 async function getText(path){const response=await fetch(ref(path));if(!response.ok)throw new Error('File unavailable');return response.text()}
}
function openViewer(title,content){const dialog=document.querySelector('#viewer');document.querySelector('#viewer-title').textContent=title;document.querySelector('#viewer-content').innerHTML=content;dialog.showModal()}
function markdown(text,e){
 let code=false,buffer=[],out=[];
 const inline=line=>e(line).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
 for(const line of text.split('\n')){if(line.trim().startsWith('```')){if(code){out.push(`<pre><code>${e(buffer.join('\n'))}</code></pre>`);buffer=[]}code=!code;continue}if(code){buffer.push(line);continue}const h=line.match(/^(#{1,6}) (.*)/);if(h){const level=Math.min(h[1].length+1,6);out.push(`<h${level}>${inline(h[2])}</h${level}>`)}else if(/^[-*] /.test(line))out.push(`<p class="doc-bullet">• ${inline(line.slice(2))}</p>`);else if(line.trim()==='---')out.push('<hr>');else if(line.trim())out.push(`<p>${inline(line)}</p>`)}if(buffer.length)out.push(`<pre><code>${e(buffer.join('\n'))}</code></pre>`);return out.join('');
}
