import {refreshHeader,refreshFooter,icon} from '../homepage/refresh-sections.js';
import {esc} from '../homepage/ui.js';

export const officeAddress='Оренбург, ул. Мало-Луговая, 3/1';
export const mapUrl=`https://yandex.ru/maps/?text=${encodeURIComponent(officeAddress)}`;
export const gisUrl=`https://2gis.ru/orenburg/search/${encodeURIComponent(officeAddress)}`;
const pageLinks=html=>html.replace(/href="#(services|news|blog|offers|mortgage)"/g,'href="homepage.html#$1"');
export const contactIcon=name=>`<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${{
 pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 mail:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 7 9 6 9-6"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',
 route:'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="M7 5h9a4 4 0 0 1 0 8H8a4 4 0 0 0 0 8h3"/>',
 close:'<path d="m6 6 12 12M18 6 6 18"/>',
}[name]||''}</svg>`;
const arrow=()=>`<span class="button-icon">${icon('diagonal')}</span>`;

export function contactsIntro(){return `<section class="c-intro r-container" aria-labelledby="contacts-title">
 <nav class="c-breadcrumbs" aria-label="Хлебные крошки"><a href="homepage.html">Главная</a><span aria-hidden="true">/</span><span aria-current="page">Контакты</span></nav>
 <div class="c-title-row"><div><p class="r-kicker"><span class="location-dot"></span> Квадрат · Оренбург</p><h1 id="contacts-title">Контакты</h1></div><p>Начнём с разговора. <br>По телефону, в письме или у нас в офисе.</p></div>
 <div class="c-overview">
  <div class="c-connect"><div class="c-panel-heading"><h2>Будем на связи</h2><span class="c-symbol">${icon('message')}</span></div>
   <div class="c-phones"><div><span class="c-label">Телефон офиса</span><a class="c-phone-primary" href="tel:+73532903350">+7 (3532) 90-33-50</a></div><div><span class="c-label">Мобильный</span><a class="c-phone-secondary" href="tel:+79228293350">+7 (922) 829-33-50</a></div></div>
   <div class="c-contact-meta"><div><span class="c-label">Электронная почта</span><a class="c-email" href="mailto:a.n.kvadrat@inbox.ru">a.n.kvadrat@inbox.ru ${icon('diagonal')}</a></div><div><span class="c-label">Время работы · Оренбург</span><p>Пн–Пт, 10:00–19:00</p><small>Сб–Вс — выходные</small></div></div>
   <div class="c-connect-actions"><a class="r-button" href="#write"><span>Написать нам</span>${arrow()}</a><button class="r-text-link" type="button" data-consult="Заказать звонок">Заказать звонок ${icon('arrow')}</button></div>
  </div>
  <a class="c-office-preview" href="#office"><div class="c-office-photo"><img src="contacts-page/assets/office-original.png" alt="Наш офис: рабочие столы и диван у большого окна" width="1080" height="1080" fetchpriority="high"></div><div class="c-office-caption"><div><span class="c-label">Приходите познакомиться</span><h2>БЦ «Евразия», 4 этаж</h2><p>Оренбург, ул. Мало-Луговая, 3/1</p></div><span class="c-round-arrow">${icon('arrow')}</span></div></a>
 </div>
 </section>`;}

export function officeSection(){return `<section class="c-office r-container" id="office" aria-labelledby="office-title">
 <div class="c-section-heading"><div><p class="r-kicker"><span>01</span> Встреча в офисе</p><h2 id="office-title">Как нас найти</h2></div><p>Оренбург, бизнес-центр «Евразия». <br>Будем рады обсудить ваши планы лично.</p></div>
 <div class="c-office-layout"><figure class="c-map"><a class="c-map-link" href="${esc(mapUrl)}" target="_blank" rel="noopener noreferrer"><span class="c-map-picture"><img src="contacts-page/assets/map-original.png" alt="Схема расположения офиса у пересечения проспекта Гагарина и Мало-Луговой улицы" width="1366" height="768" loading="lazy"></span><span class="c-map-tag">${contactIcon('pin')} Офис «Квадрат»</span><span class="c-map-action">Открыть карту ${icon('diagonal')}<span class="sr-only">— Яндекс Карты, новая вкладка</span></span></a><figcaption><span>© Яндекс · схема расположения</span><span>Актуальный маршрут — в картах</span></figcaption></figure>
 <div class="c-office-details"><div class="c-address-heading"><span class="c-label">Адрес офиса</span><span class="c-floor">4 этаж</span></div><h3>БЦ «Евразия»</h3><address>г. Оренбург, ул. Мало-Луговая, 3/1<span>Также указан как проспект Гагарина, 15/1</span></address><button type="button" class="c-copy" data-copy-address>${contactIcon('copy')}<span>Скопировать адрес</span></button>
 <div class="c-hours"><span class="c-detail-icon">${contactIcon('clock')}</span><div><h4>Часы работы</h4><dl><div><dt>Понедельник — пятница</dt><dd>10:00–19:00</dd></div><div><dt>Суббота, воскресенье</dt><dd>Выходные</dd></div></dl><p>Время местное, Оренбург</p></div></div>
 <div class="c-route-actions"><a class="r-button" href="${esc(mapUrl)}" target="_blank" rel="noopener noreferrer"><span>Яндекс Карты<span class="sr-only">, новая вкладка</span></span>${arrow()}</a><a class="c-gis" href="${esc(gisUrl)}" target="_blank" rel="noopener noreferrer">2ГИС ${icon('diagonal')}<span class="sr-only">, новая вкладка</span></a></div>
 </div></div><div class="c-visit-note">${contactIcon('route')}<p>Не получается найти офис или нужна помощь перед визитом? <a href="tel:+73532903350">Позвоните нам — подскажем.</a></p></div>
 </section>`;}

const field=(id,name,label,{type='text',hint='',required=true}={})=>`<div class="c-field"><label class="ui-field-label" for="${id}">${label}${required?' <span aria-hidden="true">*</span>':''}</label><input class="ui-input" id="${id}" name="${name}" type="${type}" ${required?'required':''} autocomplete="${name==='name'?'given-name':'tel'}" ${type==='tel'?'inputmode="tel" placeholder="+7 (___) ___-__-__" maxlength="25"':'maxlength="80" placeholder="Как к вам обращаться"'} aria-describedby="${id}-error${hint?' '+id+'-hint':''}">${hint?`<span class="c-field-hint ui-field-hint" id="${id}-hint">${hint}</span>`:''}<span class="c-field-error ui-field-error" id="${id}-error" hidden></span></div>`;

export function writeSection(){return `<section class="c-write r-container" id="write" aria-labelledby="write-title">
 <div class="c-section-heading"><div><p class="r-kicker"><span>02</span> Ваш вопрос</p><h2 id="write-title">Давайте обсудим</h2></div><p>Покупка, продажа или работа агентства. <br>Выберите, кому адресовать сообщение.</p></div>
 <div class="c-write-layout"><aside class="c-director" aria-labelledby="director-title"><div class="c-director-copy"><p class="r-kicker">Личный контакт</p><h3 id="director-title">Можно обратиться<br>к директору</h3><p>Если хотите поделиться отзывом <br>или обсудить важный вопрос.</p><button type="button" class="c-director-action" data-to-director>Написать директору ${icon('diagonal')}</button></div><img src="references/kvadrat-ds/assets/images/fig/880316dc7fbbcd57.png" alt="Олеся Войцеховская, директор агентства Квадрат" width="600" height="973" loading="lazy"><div class="c-director-signature"><strong>Олеся Войцеховская</strong><span>Директор агентства «Квадрат»</span></div></aside>
 <div class="c-form-surface ui-fields-raised"><form method="dialog" class="c-contact-form" id="message-form" novalidate aria-describedby="message-form-note message-required-note"><fieldset class="c-recipient"><legend>Кому написать</legend><div class="ui-segments ui-segments--wrap"><label class="ui-segment"><input type="radio" name="recipient" value="agency" checked><span>В агентство</span></label><label class="ui-segment"><input type="radio" name="recipient" value="director"><span>Директору</span></label></div></fieldset><p class="c-required-note" id="message-required-note">Поля со звёздочкой обязательны</p>
 <div class="c-form-row">${field('contact-name','name','Ваше имя')}${field('contact-phone','phone','Телефон',{type:'tel',hint:'Для ответа на ваш вопрос'})}</div>
 <div class="c-field"><label class="ui-field-label" for="contact-message">Ваш вопрос <span aria-hidden="true">*</span></label><textarea class="ui-input" id="contact-message" name="message" rows="4" maxlength="2000" required placeholder="Расскажите, чем мы можем помочь" aria-describedby="contact-message-error contact-message-hint"></textarea><div class="c-message-hints"><span class="c-field-hint ui-field-hint" id="contact-message-hint">Не указывайте паспортные данные</span><span class="c-field-hint ui-field-hint" data-message-count aria-hidden="true">0 / 2000</span></div><span class="c-field-error ui-field-error" id="contact-message-error" hidden></span></div>
 <div class="c-consent-field"><label class="c-consent ui-choice"><input id="contact-consent" name="consent" class="ui-check" type="checkbox" required aria-describedby="contact-consent-error"><span>Даю согласие на обработку персональных данных для ответа на обращение <span aria-hidden="true">*</span></span></label><button class="c-privacy" type="button" data-privacy>Об обработке данных</button><span class="c-field-error ui-field-error" id="contact-consent-error" hidden></span></div>
 <div class="c-submit-row"><button class="r-button" type="submit"><span>Отправить сообщение</span>${arrow()}</button><p id="message-form-note">Демонстрационная форма. <br>Сообщение не отправляется.</p></div><div class="c-form-result" role="status" aria-live="polite" tabindex="-1" hidden></div>
 </form><div class="c-email-alternative">Удобнее по почте? <a data-recipient-email href="mailto:a.n.kvadrat@inbox.ru">a.n.kvadrat@inbox.ru ${icon('diagonal')}</a></div></div></div>
 </section>`;}

export function callbackDialog(){return `<dialog class="c-dialog" id="callback-dialog" aria-labelledby="callback-title"><button class="c-dialog-close" type="button" data-close-dialog aria-label="Закрыть">${contactIcon('close')}</button><p class="r-kicker">Связаться с агентством</p><h2 id="callback-title">Заказать звонок</h2><p class="c-dialog-description">Оставьте номер телефона, по которому с вами можно связаться.</p><form method="dialog" class="c-contact-form" id="callback-form" novalidate aria-describedby="callback-note callback-required-note"><p class="c-required-note" id="callback-required-note">Поля со звёздочкой обязательны</p>${field('callback-name','name','Ваше имя')}${field('callback-phone','phone','Телефон',{type:'tel'})}<div class="c-consent-field"><label class="c-consent ui-choice"><input id="callback-consent" name="consent" class="ui-check" type="checkbox" required aria-describedby="callback-consent-error"><span>Даю согласие на обработку данных для обратного звонка <span aria-hidden="true">*</span></span></label><span class="c-field-error ui-field-error" id="callback-consent-error" hidden></span></div><button class="r-button" type="submit"><span>Жду звонка</span>${arrow()}</button><p class="c-demo-note" id="callback-note">Демонстрационная форма. Заявка не отправляется, данные не сохраняются.</p><div class="c-form-result" role="status" aria-live="polite" tabindex="-1" hidden></div></form></dialog>`;}

export function contactsPage(){return `${pageLinks(refreshHeader({theme:'light',current:'contacts'}))}<main id="contacts-main" tabindex="-1">${contactsIntro()}${officeSection()}${writeSection()}</main>${pageLinks(refreshFooter()).replace('Концепция главной · данные демонстрационные','Макет страницы контактов')}${callbackDialog()}<dialog class="c-dialog" id="privacy-dialog" aria-labelledby="privacy-title"><button type="button" class="c-dialog-close" data-close-dialog aria-label="Закрыть">${contactIcon('close')}</button><p class="r-kicker">Обработка данных</p><h2 id="privacy-title">Данные в этом макете</h2><p class="c-dialog-description">Форма показывает пример обращения. Введённые данные никуда не отправляются и не сохраняются. Не указывайте реальные персональные данные.</p><p class="c-dialog-description">Для рабочего сайта здесь потребуется утверждённый документ о согласии на обработку персональных данных.</p><button type="button" class="r-button" data-close-dialog>Понятно ${arrow()}</button></dialog><noscript><p class="c-noscript r-container">Телефоны, почта и ссылки на карты доступны. Для демонстрационных форм и копирования адреса включите JavaScript.</p></noscript>`;}
