import {art,image,esc,action} from './ui.js';
export const services=[
 {title:'<b>Продажа</b><br>недвижимости',text:'Организуем продажу вашей недвижимости в Оренбурге в короткие сроки по максимально возможной рыночной цене.',asset:'s1.png'},
 {title:'<b>Покупка</b><br>недвижимости',rows:[['Студии','от 700 000 руб'],['Однокомнатные','от 900 000 руб'],['Двухкомнатные','от 1 700 000 руб'],['Трехкомнатные','от 2 100 000 руб']],asset:'s2.png'},
 {title:'<b>Покупка<br>от застройщика</b>',rows:[['Сданные','от 1 100 000 руб'],['Строящиеся','от 900 000 руб']],asset:'s3.png'},
 {title:'<b>Аренда</b><br>недвижимости',text:'Поможем нанимателям снять жилье или коммерческую недвижимость, а владельцам недвижимости найти желаемых нанимателей.',asset:'s4.png'},
 {title:'<b>Оценка</b><br>недвижимости',text:'Проведем оценку объекта недвижимости с выдачей официального отчета об оценке.',asset:'s5.png'},
 {title:'<b>Юридическое<br>сопровождение</b>',text:'Подготовим документы и проведем сопровождение сделок купли-продажи недвижимости любой сложности.',asset:'s6.png'}
];
export function serviceCard(item,index){const label=item.title.replace(/<br>/g,' ').replace(/<[^>]+>/g,'');return `<article class="service-card service-${index+1}"><span class="card-number" aria-hidden="true">0${index+1}</span><h3><button data-consult="${esc(label)}">${item.title}</button></h3>${item.rows?`<ul class="service-prices">${item.rows.map(([title,price])=>`<li><button data-consult="${esc(title)}">${title}</button> <small>${price}</small></li>`).join('')}</ul>`:`<p>${item.text}</p>`}${image(art(item.asset),'','service-art','loading="lazy"')}</article>`;}
export function propertyCard(item){return `<article class="property-card"><a class="property-photo" href="property-object.html" aria-label="${item.rooms}-комнатная квартира, ${esc(item.address)}">${image(item.image,`${item.rooms}-комнатная квартира`,'','loading="lazy" width="270" height="169"')}</a><div class="property-body"><h3><a href="property-object.html">${item.rooms}-комнатная квартира</a></h3><p class="property-address">${esc(item.address)}</p><dl class="property-specs"><div><dt>Площадь:</dt><dd>${item.area} м<sup>2</sup></dd></div><div><dt>Этаж:</dt><dd>${esc(item.floor)}</dd></div><div><dt>${item.walls?'Стены:':'Сдача:'}</dt><dd>${esc(item.walls||item.delivery)}</dd></div></dl><p class="property-price">${item.price.toLocaleString('ru-RU')} руб</p><p class="price-per-meter">${(item.pricePerMeter??73000).toLocaleString('ru-RU')} руб/м<sup>2</sup></p><a class="property-open" href="property-object.html" aria-label="Открыть квартиру на ${esc(item.address)}">${image(art('rmore.svg'),'','property-open-icon','width="36" height="36"')}</a></div></article>`;}
export function promoCard(item){return `<article class="promo-card ${item.light?'light':''}"><p class="eyebrow">${item.eyebrow}</p><h3><b>${item.title}</b><br>${item.subtitle}</h3><p class="promo-description">Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus.</p>${action('Подробнее',item.title)}${image(item.image,'','promo-art','loading="lazy"')}</article>`;}
export function agentCard(item){return `<article class="agent-card"><div class="portrait">${image(item.image,item.name,'','loading="lazy"')}</div><div class="agent-info"><p class="agent-award"><b>Лучший риэлтор</b> ${item.period}</p><div class="agent-details"><div><h3>${item.name}</h3><p>Специалист по недвижимости</p></div><div class="agent-contact"><a href="tel:${item.phone.replace(/[^+\d]/g,'')}">${item.phone}</a><a href="mailto:${item.email}">${item.email}</a></div></div></div></article>`;}
export function newsCard(item){return `<article class="news-card"><button data-news="${item.id}" class="news-image" aria-label="${esc(item.title)}">${image(item.image,item.title,'','loading="lazy" width="231" height="231"')}</button><div class="news-copy"><p class="card-category">${item.category}</p><h3><button data-news="${item.id}">${item.title}</button></h3><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.</p><time datetime="2018-11-21">21 ноября 2018</time></div></article>`;}
export function articleCard(item){return `<article class="article-card"><p class="card-category">${item.category}</p><h3><button data-article="${item.id}">${item.title}</button></h3><p class="article-excerpt">Как выбрать лучший вариант среди стремительно развивающихся современных технологий</p><div class="article-author"><div class="portrait">${image(item.image,item.author,'','loading="lazy"')}</div><p>${item.author}</p><small>${item.role}</small></div></article>`;}
