import {searchFields} from './search-fields.js';
import {art,image,action,heading,more,contacts,social,photo,carouselControls,esc} from './ui.js';
import {services,serviceCard,propertyCard,promoCard,agentCard,newsCard,articleCard} from './cards.js';
import {properties,categories,agents,news,articles} from './data.js';
export function header({light=false,contactDetails,linkBase=""}={}){return `<a class="site-pages-link" href="index.html#pages">← Все страницы</a><header><div class="navigation"><div class="container nav-inner"><nav aria-label="Основная навигация"><a href="property-catalog.html">Недвижимость <i></i></a><a href="${linkBase}#services">Услуги <i></i></a><a href="${linkBase}#offers">Спецпредложения</a><a href="${linkBase}#mortgage">Цены</a><a href="${linkBase}#news">Квадрат изнутри</a><a href="${linkBase}#contacts">Контакты</a></nav>${social()}</div></div><div class="container identity"><a href="homepage.html" aria-label="Квадрат — главная">${image(art(light?'logo-dark.svg':'logo.svg'),'Квадрат — агентство недвижимости','logo','width="190" height="99"')}</a>${contacts(contactDetails)}</div></header>`;}
export function hero(){return `${header()}<section class="hero container" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">Агентство недвижимости</p><h1 id="hero-title">Ваш личный агент<br>по недвижимости</h1><p class="hero-description">Отстаивание Ваших интересов и надежная поддержка в любой ситуации для решения самых трудных квартирных вопросов в Оренбурге</p><div class="hero-actions">${action('Заказать консультацию')}<button class="video-button" data-video><span class="play-shell"><span class="play" aria-hidden="true">▶</span></span>Видео</button></div></div><div class="hero-statistics"><div class="stat stat-price"><span class="radar" aria-hidden="true"><i></i></span><div><p>Квартиры от<br>застройщика от</p><div class="stat-value"><strong>650</strong><span>тыс.<br>руб.</span></div></div></div><div class="stat stat-rate"><span class="radar" aria-hidden="true"><i></i></span><div><p>получение<br>Ипотеки под</p><div class="stat-value"><strong>8,4</strong><span>%</span></div></div></div></div><a href="#services" class="scroll-cue"><span aria-hidden="true"></span>Дальше</a></section>`;}
export function serviceSection(){return `<section class="services container" id="services">${heading('Полный цикл','Услуги агентства',more('Все услуги','#services'))}<div class="services-grid">${services.map(serviceCard).join('')}</div></section>`;}
export function mortgage(copy){const items=[['Ипотека без<br>первого взноса','save-money.svg'],['Рефинансирование<br>ипотеки','coin.svg'],['Материнский<br>капитал','stroller.svg'],['Военная<br>ипотека','soldier.svg']];return `<section class="mortgage container" id="mortgage">${heading('Низкий процент','Ипотечное<br>кредитование',`<p class="section-description">${esc(copy['166'])}</p>`)}${image(art('percent.svg'),'','percent-decoration')}<div class="mortgage-grid"><article class="mortgage-feature"><h3><button data-calculator>Помощь в получении ипотеки. Ипотечный калькулятор.</button></h3><p>${esc(copy['165'])}</p></article>${items.map(([title,icon])=>`<article class="mortgage-card"><h3><button data-consult="${title.replace(/<br>/g,' ')}">${title}</button></h3>${image(art(icon))}</article>`).join('')}</div><button class="calculator-art" data-calculator aria-label="Открыть ипотечный калькулятор">${image(art('image-calc.png'),'','', 'loading="lazy"')}</button>${image(art('plan.png'),'','mortgage-plan','loading="lazy"')}</section>`;}
export function offers(){const promos=[{eyebrow:'Без комиссии',title:'Офис продаж',subtitle:'от застройщиков',image:art('iconpersent.png')},{eyebrow:'Просто',title:'Более 10 банков',subtitle:'в одном месте',image:photo('4ea7bdf126e22064.png'),light:true},{eyebrow:'Удобно',title:'15 застройщиков',subtitle:'в одном месте',image:art('builders.png')}];return `<section id="offers" class="offers container"><div class="promo-grid">${promos.map(promoCard).join('')}</div><div class="agents-grid">${agents.map(agentCard).join('')}</div></section>`;}
export function catalog(copy){return `<section class="catalog container" id="catalog">${heading('Большая база','Каталог<br>недвижимости',`<p class="section-description">${esc(copy['172'])}</p>`)}<div class="catalog-tabs" role="tablist" aria-label="Тип недвижимости">${categories.map((name,i)=>`<button role="tab" id="category-${i}" aria-controls="property-list" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-category="${i}">${name}</button>`).join('')}</div><div class="property-grid" id="property-list" role="tabpanel" aria-labelledby="category-0">${properties.map(propertyCard).join('')}</div><p class="catalog-message" role="status" hidden></p>${carouselControls('catalog','Все объекты',4,'property-catalog.html')}</section>`;}
export function search(){return `<section class="search-section container" id="search"><div class="search-panel">${heading('Подбор','Найдем объект<br><span>по вашим пожеланиям</span>')}${image(art('search_plan.png'),'','search-plan','loading="lazy"')}<form action="property-catalog.html" method="get" class="property-search" aria-label="Подбор недвижимости">${searchFields()}<button class="search-submit" type="submit" aria-label="Найти недвижимость"><span></span></button></form></div></section>`;}
export function about(copy){return `<div class="about-wash"><section id="about" class="about container"><div class="about-picture">${image(photo('5205626077cfec78.jpg'),'Жилые кварталы города','','loading="lazy"')}</div><div class="about-copy">${heading('Профессиональная команда','Хороший риэлтор -<br>ваш надежный союзник')}<p>${esc(copy['173'])}</p>${action('Подробнее об агентстве','Об агентстве')}</div></section></div>`;}
export function editorial(copy){return `<section class="editorial container">${heading('Тестовое','Заголовок')}${image(art('logo-dark.svg'),'Квадрат','editorial-logo','loading="lazy"')}<p class="editorial-lead">${esc(copy['545'])}</p><div class="editorial-body">${copy['544'].split('\n').map(p=>`<p>${esc(p)}</p>`).join('')}</div></section>`;}
export function consultation(copy){return `<section class="consultation" id="consultation"><div class="container consultation-inner"><div class="consultation-copy">${heading('Консультация','Напишите нам')}<p>${esc(copy['562'])}</p>${action('Оставить заявку')}</div>${image(photo('4deffc558c2fd253.png'),'','consultation-house','loading="lazy"')}${image(photo('880316dc7fbbcd57.png'),'Гульмира Суеналимова','consultation-agent','loading="lazy"')}<p class="consultation-signature"><b>Гульмира Суеналимова</b><small>Риелтор, директор АН &quot;Квадрат&quot;</small></p></div></section>`;}
export function newsSection(){return `<section class="news container" id="news">${heading('Актуальное','Новости',`<label class="news-toggle"><input type="checkbox" role="switch" id="offers-only"><span></span>Только акции</label>`)}<div class="news-grid" id="news-list">${news.map(newsCard).join('')}</div>${carouselControls('news','Все новости')}</section>`;}
export function blog(copy){return `<section class="blog container" id="blog">${heading('Советы риелторов','Наш блог',`<p class="section-description">${esc(copy['421'])}</p>`)}<div class="article-grid">${articles.map(articleCard).join('')}</div>${carouselControls('blog','Все статьи')}</section>`;}
export function footer(copy,{contactDetails,linkBase=""}={}){return `<footer class="footer" id="contacts"><div class="container"><div class="footer-identity"><a href="homepage.html">${image(art('logo.svg'),'Квадрат','logo','width="190" height="99" loading="lazy"')}</a>${contacts(contactDetails)}</div><div class="footer-columns">${[['Услуги','536','#services'],['Ипотека','538','#mortgage'],['Объекты','540','#catalog'],['Об агентстве','542','#news']].map(([title,id,href])=>`<nav aria-label="${title}"><h3>${title}</h3>${copy[id].split('\n').map(label=>`<a href="${id==='540'?'property-catalog.html':linkBase+(label==='Жизнь Квадрата'?'#news':label==='Новости'?'#news':label==='Блог'?'#blog':label==='Контакты'?'#contacts':href)}">${esc(label)}</a>`).join('')}</nav>`).join('')}</div></div><div class="copyright"><div class="container"><p>© 2018 Все права защищены</p>${social()}</div></div></footer>`;}
