import {escapeHtml} from '../html.js';
export const esc=escapeHtml;
export const art=name=>`homepage/assets/${name}`;
export const photo=name=>`references/kvadrat-ds/assets/images/fig/${name}`;
export const image=(src,alt='',className='',extra='')=>`<img src="${esc(src)}" alt="${esc(alt)}" class="${className}" ${extra}>`;
export const action=(label,topic=label,className='')=>`<button class="pill ${className}" data-consult="${esc(topic)}">${esc(label)}</button>`;
export const heading=(eyebrow,title,extra='')=>`<div class="section-heading"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${extra}</div>`;
export const arrow=(direction='right')=>`<span class="arrow-icon arrow-icon-${direction}" aria-hidden="true"></span>`;
export const more=(label,href)=>`<a class="more" href="${href}">${label}${arrow()}</a>`;
export function contacts(details){if(details){const [address,extra='']=details.address.split(' (');return `<div class="contacts"><p class="address"><span class="contact-label">Адрес:</span><strong>${esc(address)}</strong><br>${extra?'('+esc(extra):''}</p>${details.phones.map((phone,index)=>`<p class="phone"><span class="contact-label">Телефон:</span><a href="tel:${phone.replace(/[^+\d]/g,'')}">${esc(phone)}</a>${index===0?'<small>Viber, What’s App</small>':'<button class="text-button" data-consult="Заказать звонок">Заказать звонок</button>'}</p>`).join('')}</div>`;}return `<div class="contacts"><p class="address"><strong>г. Астана, БЦ "Астана", 4 этаж</strong><br>(Астанинская, 3/1; Северная 15/1)</p><p class="phone"><a href="tel:+79997773350">+7 (999) 777-33-50</a><small>Viber, What’s App</small></p><p class="phone"><a href="tel:+73444944444">+7 (3444) 94-44-44</a><button class="text-button" data-consult="Заказать звонок">Заказать звонок</button></p></div>`;}
export function social(){return `<div class="social"><span class="open-status">Сейчас открыты</span><a href="#contacts" aria-label="ВКонтакте">${image(art('vk.svg'))}</a><a class="instagram" href="#contacts" aria-label="Instagram"><span></span></a><a href="#contacts" aria-label="Одноклассники">${image(art('ok.svg'))}</a></div>`;}
export function carouselControls(id,label,count=4,href=`#${id}`){return `<div class="carousel-controls">${more(label,href)}<div class="carousel-dots" aria-label="Выбор карточки">${Array.from({length:count},(_,i)=>`<button data-carousel="${id}" data-index="${i}" aria-label="Карточка ${i+1}" aria-pressed="${i===0}"></button>`).join('')}</div><div class="carousel-arrows"><button data-carousel="${id}" data-step="-1" aria-label="Предыдущая карточка">${arrow('left')}</button><button data-carousel="${id}" data-step="1" aria-label="Следующая карточка">${arrow()}</button></div></div>`;}
